workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build .ipa
        script: |
          xcodebuild -project WordCounterSpeechApp.xcodeproj -scheme WordCounterSpeechApp -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/WordCounterSpeechApp.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/WordCounterSpeechApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR/export
    artifacts:
      - export/*.ipa
